name: Terraform OCI IaC Workflow

on:
  workflow_dispatch:
    inputs:
      account_number:
        description: "choose account"
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'

      operation:
        description: "terraform action"
        required: true
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo bash ./scripts/install-terraform.sh
      
      - name: Run Terraform for selected account
        run: |
          DECODED_JSON=$(echo '${{ secrets.OCI_ACCOUNTS_JSON }}' | base64 -d)
          TEMP_JSON_PATH="${{ runner.temp }}/accounts.json"

          echo "Creating temporary config file at: $TEMP_JSON_PATH"

          echo "🔍 Validating JSON structure:"
          if echo "$DECODED_JSON" | jq empty 2>/dev/null; then
              echo "✅ JSON is valid"
          else
              echo "❌ JSON is invalid - showing errors:"
              echo "$DECODED_JSON" | jq empty
              exit 1
          fi

          echo "$DECODED_JSON" > "$TEMP_JSON_PATH"
      
          bash ./scripts/deploy.sh "$TEMP_JSON_PATH" ${{ github.event.inputs.account_number }} ${{ github.event.inputs.operation }} $(pwd)/accounts
      
          rm -rf "$TEMP_JSON_PATH"

      - name: Clean up Terraform sensitive files
        if: always()
        working-directory: ./accounts
        run: |
          echo "🧹 Final cleanup of sensitive files from the workspace..."
          rm -f private_key.pem
          rm -rf .terraform
          rm -rf .terraform.lock.hcl
          rm -rf .terraform.tfstate
